# Generated by Django 4.2.5 on 2023-09-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Semester', to='subject.subjects')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='subject.subjects')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Year', to='subject.subjects')),
            ],
        ),
    ]
