# Generated by Django 4.2.5 on 2023-09-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_class_student_subject_teacher_delete_register_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
