# Generated by Django 4.2.5 on 2023-09-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_remove_class_teacher_alter_class_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='subject.subject'),
        ),
    ]
