# Generated by Django 4.2.5 on 2023-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_remove_student_subjects_class_max_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='max_seats',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='class',
            name='remaining_seats',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='class',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
