# Generated by Django 4.2.5 on 2023-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_remove_class_remaining_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
