# Generated by Django 4.2.5 on 2023-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_class_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='class',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default=None, max_length=10),
        ),
    ]
