# Generated by Django 4.2.5 on 2023-10-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='subject.subject', unique=True),
        ),
    ]
