# Generated by Django 4.2.5 on 2023-10-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0014_alter_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=None, max_length=10),
        ),
    ]
