name: Testing
on:
  push:
    branches:
      - testing

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Django unit tests
      run: |
        pip install --user -r requirements.txt
        python3 manage.py makemigrations
        python3 manage.py migrate
        coverage run --source='.' manage.py test
        coverage report
        
